### PR TITLE
Add support to Arduino UNO board

### PR DESCRIPTION
**Pull request by mouradelbellili**
Updated WiFiNINA_Pinout_Generic.h by adding pinouts definitions to be able to communicate with nina module.
Pinouts configuration was tested and we were able to connect to WiFi with Arduino UNO board.

### CODE REVIEW

**Comment by khoih-prog** [comment]
Hi @mouradelbellili 

Thanks for your PR. Could you please provide more info, such as

1. Which board (Arduino UNO ??) and which WiFiNINA module (W102, ??) you're using
2. Debug terminal output to verify
3. Wiring / connection between UNO and WiFiNINA module

The supplied info will be very useful to other users as well as me because I don't have the similar settings to test / verify before merging the PR.

BR,

**Comment by mouradelbellili** [comment]
1. I used Arduino UNO Rev3 and Adafruit HUZZAH32 – ESP32 Feather Board such as WiFi module (firmware for the esp32 : [https://github.com/arduino/nina-fw](url))
2. I tested ConnectWithWEP example on the WiFiNINA_Generic library 
image

3. Wiring between UNO and ESP32 boards
image

**Comment by khoih-prog** [comment]
Thank so much for your impressive info. I'm merging your PR now and will create a new release soon.

Best Regards,

**Review by khoih-prog — APPROVED** [review]

**Review by khoih-prog — APPROVED** [review]

**Comment by mouradelbellili** [comment]
Thank you :)

**Comment by khoih-prog** [comment]
I'll add to new releasee v1.8.12 the support to almost all AVR boards using your settings as follows:

```
#elif defined(__AVR_ATmega2560__)    || defined(__AVR_ATmega2561__)   || defined(__AVR_ATmega1280__) || defined(__AVR_ATmega1281__)    || \
      defined(__AVR_ATmega640__)   || defined(__AVR_ATmega641__)    || defined(__AVR_ATmega644__)  || defined(__AVR_ATmega644A__)      || \
      defined(__AVR_ATmega644P__)  || defined(__AVR_ATmega644PA__)  || defined(ARDUINO_AVR_UNO)    || defined(ARDUINO_AVR_NANO)        || \
      defined(ARDUINO_AVR_MINI)    || defined(ARDUINO_AVR_ETHERNET) || defined(ARDUINO_AVR_FIO)    || defined(ARDUINO_AVR_BT)          || \
      defined(ARDUINO_AVR_LILYPAD) || defined(ARDUINO_AVR_PRO)      || defined(ARDUINO_AVR_NG) || defined(ARDUINO_AVR_UNO_WIFI_DEV_ED) || \
      defined(ARDUINO_AVR_DUEMILANOVE)  || defined(ARDUINO_AVR_FEATHER328P) || defined(ARDUINO_AVR_METRO) || defined(ARDUINO_AVR_PROTRINKET5) || \
      defined(ARDUINO_AVR_PROTRINKET3)  || defined(ARDUINO_AVR_PROTRINKET5FTDI) || defined(ARDUINO_AVR_PROTRINKET3FTDI) || \
      defined(ARDUINO_AVR_LEONARDO) || defined(ARDUINO_AVR_LEONARDO_ETH) || defined(ARDUINO_AVR_YUN) || defined(ARDUINO_AVR_MICRO) || \
      defined(ARDUINO_AVR_ESPLORA)  || defined(ARDUINO_AVR_LILYPAD_USB)  || defined(ARDUINO_AVR_ROBOT_CONTROL) || \
      defined(ARDUINO_AVR_ROBOT_MOTOR) || defined(ARDUINO_AVR_CIRCUITPLAY)  || defined(ARDUINO_AVR_YUNMINI) || defined(ARDUINO_AVR_INDUSTRIAL101) || \
      defined(ARDUINO_AVR_LININO_ONE) || defined(ARDUINO_AVR_FLORA8 ) || defined(ARDUINO_AVR_FEATHER32U4) || defined(ARDUINO_AVR_CIRCUITPLAY) || \
      defined(ARDUINO_AVR_ITSYBITSY32U4_5V) || defined(ARDUINO_AVR_ITSYBITSY32U4_3V) || defined(ARDUINO_AVR_BLUEFRUITMICRO) || \
      defined(ARDUINO_AVR_ADAFRUIT32U4) || defined(__AVR_ATmega32U4__) || defined(ARDUINO_AVR_MAKEYMAKEY ) || defined(ARDUINO_AVR_PROMICRO) || \
      defined(ARDUINO_AVR_FIOV3) || defined(ARDUINO_AVR_QDUINOMINI) || defined(ARDUINO_AVR_LILYPAD_ARDUINO_USB_PLUS_BOARD ) || \
      defined(__AVR_ATmega328P__) || defined(ARDUINO_AVR_DIGITAL_SANDBOX ) || defined(ARDUINO_REDBOT) || defined(ARDUINO_AVR_SERIAL_7_SEGMENT) || \
      defined(__AVR_ATmega128RFA1__) || defined(ARDUINO_ATMEGA128RFA1_DEV_BOARD)
      
  // To define pin out for WiFiNINA here
  //#define PIN_SPI_SS    (4)
  //#define PIN_SPI_MOSI  (11)
  //#define PIN_SPI_MISO  (12)
  //#define PIN_SPI_SCK   (13)

  #define PINS_COUNT           (60u)
  //NINA
  #define NINA_GPIO0  (2u)                            
  #define NINA_RESETN (7u)
  #define NINA_ACK    (8u)
  #define SPIWIFI_SS       4   
  #define SPIWIFI_ACK      8    
  #define SPIWIFI_RESET    7
  
  #warning You have to modify pin usage according to actual connection for AVR boards

#else
...
```

Thanks for your contributions,

BR,

**Comment by mouradelbellili** [comment]
Mega 2560/1280 already exists :) 
image

**Comment by khoih-prog** [comment]
Oh, too many boards I forgot. Will remove Mega, keep the remaining boards (other 328p, 32U4, 16u4, etc.). Thanks,

**Comment by khoih-prog** [comment]
Hi @mouradelbellili 

[**WiFiNINA_Generic** Releases v1.8.12](https://github.com/khoih-prog/WiFiNINA_Generic/releases/tag/v1.8.12) has just been published. Your contribution is noted in [**Contributions and Thanks**](https://github.com/khoih-prog/WiFiNINA_Generic#contributions-and-thanks).

Looking forward to receiving more of your contribs.

BR,

**Pull request merged**
